/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.12.0
 * Tue, 24 Mar 2026 20:27:15 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();
_pGlob.css3Objects = new WeakMap();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectName(obj) {
        // auto-generated from a multi-material object, use parent name instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.name;
        } else {
            return obj.name;
        }
    }
        
    function getObjectUUID(obj) {
        // auto-generated from a multi-material object, use parent UUID instead
        if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
            return obj.parent.uuid;
        } else {
            return obj.uuid;
        }
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function initObjectPicking(callback, eventType, mouseDownUseTouchStart=false,
            allowedMouseButtons=null) {
    
        // css renderer prevents interacting with canvas, in that case we assign events on container
        const elem = appInstance.cssRenderer ? appInstance.container : appInstance.renderer.domElement;
        bindListener(elem, eventType, pickListener);
    
        if (eventType === 'mousedown') {
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, pickListener);
    
        } else if (eventType === 'dblclick') {
    
            let prevTapTime = 0;
    
            function doubleTapCallback(event) {
                const now = new Date().getTime();
                const timesince = now - prevTapTime;
    
                if (timesince < 600 && timesince > 0) {
                    pickListener(event);
                    prevTapTime = 0;
                    return;
                }
    
                prevTapTime = new Date().getTime();
            }
    
            const touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
            bindListener(elem, touchEventName, doubleTapCallback);
        }
    
        const raycaster = new v3d.Raycaster();
    
        function pickListener(event) {
    
            // to handle unload in loadScene puzzle
            if (!appInstance.getCamera()) {
                return;
            }
    
            event.preventDefault();
    
            let xNorm = 0;
            let yNorm = 0;
            if (event instanceof MouseEvent) {
                if (allowedMouseButtons !== null && allowedMouseButtons.indexOf(event.button) === -1) {
                    return;
                }
                xNorm = event.offsetX / elem.clientWidth;
                yNorm = event.offsetY / elem.clientHeight;
            } else if (event instanceof TouchEvent) {
                const rect = elem.getBoundingClientRect();
                xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
                yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
            }
    
            _pGlob.screenCoords.x = xNorm * 2 - 1;
            _pGlob.screenCoords.y = -yNorm * 2 + 1;
            raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
    
            const objList = [];
            appInstance.scene.traverse(obj => objList.push(obj));
    
            const intersects = raycaster.intersectObjects(objList, false);
            callback(intersects, event);
        }
    }
        
    function isObjectAmongObjects(objNameToCheck, objUUIDToCheck, objNames) {
        if (!objNameToCheck) {
            return false;
        }
    
        // COMPAT: <4.10, when calling with 2 arguments
        if (Array.isArray(objUUIDToCheck)) {
            objNames = objUUIDToCheck;
            objUUIDToCheck = objNameToCheck;
        }
    
        for (let i = 0; i < objNames.length; i++) {
            const objName = objNames[i];
    
            // COMPAT: < 4.10 (4.9), old engine, new puzzles
            const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
            if ((isID ? objUUIDToCheck : objNameToCheck) === objName) {
                return true;
            } else {
                // also check children which are auto-generated for multi-material objects
                const obj = getObjectByName(objName);
                if (obj && obj.type === 'Group') {
                    for (let j = 0; j < obj.children.length; j++) {
                        // if parent referred by UUID, compare children also by UUID
                        if (isID ? (objUUIDToCheck === obj.children[j].uuid) : (objNameToCheck === obj.children[j].name)) {
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }

    return {
        getObjectByName, getObjectName, getObjectUUID, initObjectPicking,
        isObjectAmongObjects, retrieveObjectNames,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};

PL.loadedLibraries = PL.loadedLibraries || [];



PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    
    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



var PROC = {
    
};

var VARS = Object.defineProperties({}, {
    'Boton Activado': { get: function() { return Boton_Activado; }, set: function(val) { Boton_Activado = val; } },
    '-Q1': { get: function() { return _Q1; }, set: function(val) { _Q1 = val; } },
    'existe_variable': { get: function() { return existe_variable; }, set: function(val) { existe_variable = val; } },
    '-KM1': { get: function() { return _KM1; }, set: function(val) { _KM1 = val; } },
    '-Q2': { get: function() { return _Q2; }, set: function(val) { _Q2 = val; } },
    'GI L208S': { get: function() { return GI_L208S; }, set: function(val) { GI_L208S = val; } },
    'XD3-24RT-C': { get: function() { return XD3_24RT_C; }, set: function(val) { XD3_24RT_C = val; } },
    '-K2': { get: function() { return _K2; }, set: function(val) { _K2 = val; } },
    'objeto_detectado': { get: function() { return objeto_detectado; }, set: function(val) { objeto_detectado = val; } },
    '-K3': { get: function() { return _K3; }, set: function(val) { _K3 = val; } },
    '-K4': { get: function() { return _K4; }, set: function(val) { _K4 = val; } },
    '-K5': { get: function() { return _K5; }, set: function(val) { _K5 = val; } },
    '-K6': { get: function() { return _K6; }, set: function(val) { _K6 = val; } },
    '-K7': { get: function() { return _K7; }, set: function(val) { _K7 = val; } },
    'Fuente de Voltaje 24v 5A:1': { get: function() { return Fuente_de_Voltaje_24v_5A_1; }, set: function(val) { Fuente_de_Voltaje_24v_5A_1 = val; } },
    '-S1': { get: function() { return _S1; }, set: function(val) { _S1 = val; } },
    '-S2': { get: function() { return _S2; }, set: function(val) { _S2 = val; } },
    '-S3': { get: function() { return _S3; }, set: function(val) { _S3 = val; } },
    'TS3 700-M': { get: function() { return TS3_700_M; }, set: function(val) { TS3_700_M = val; } },
    'LP7510': { get: function() { return LP7510; }, set: function(val) { LP7510 = val; } },
});

var Boton_Activado, _Q1, existe_variable, _KM1, _Q2, GI_L208S, XD3_24RT_C, _K2, objeto_detectado, _K3, _K4, _K5, _K6, _K7, Fuente_de_Voltaje_24v_5A_1, _S1, _S2, _S3, TS3_700_M, LP7510;

// setActiveCamera puzzle
function setActiveCamera(camName) {
    var camera = PzLib.getObjectByName(camName);
    if (!camera || !camera.isCamera || appInstance.getCamera() == camera)
        return;
    appInstance.setCamera(camera);
}

// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, useID, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        useID: useID,
        callbacks: [cbDo, cbIfMissedDo]
    });

    PzLib.initObjectPicking(function(intersects, event) {

        let isPicked = false;

        const maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (let i = 0; i < maxIntersects; i++) {
            const obj = intersects[i].object;

            const objName = PzLib.getObjectName(obj);
            const objUUID = PzLib.getObjectUUID(obj);
            const objNames = PzLib.retrieveObjectNames(objSelector);

            if (PzLib.isObjectAmongObjects(objName, objUUID, objNames)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = useID ? objUUID : objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}



Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// --- SOLUCIÓN PARA EL ERROR DE \'LENGTH\' ---' + '\n' +
'if (!app.postprocessing) {' + '\n' +
'    // Solo intentamos activar si el renderizador está realmente listo' + '\n' +
'    if (app.renderer && app.scene && app.getCamera()) {' + '\n' +
'        try {' + '\n' +
'            app.enablePostprocessing();' + '\n' +
'        } catch (e) {' + '\n' +
'            console.warn("Verge3D aún se está preparando... reintentando en el próximo clic.");' + '\n' +
'            return; // Salimos del clic para evitar que el error rompa el resto del script' + '\n' +
'        }' + '\n' +
'    } else {' + '\n' +
'        return; // No hacemos nada hasta que el motor esté listo' + '\n' +
'    }' + '\n' +
'}' + '\n' +
'')))(appInstance, v3d, PL, VARS, PROC);

setActiveCamera('Camara Frontal');
Boton_Activado = 'Ninguno';
_Q1 = ['-Q1', '-KM1', 'GI L208S', '358288:1', '358288:2', '358288:3', 'Cable 1', 'Cable 2', 'Cable 3', 'Cable 7', 'Cable 8', 'Cable 5', 'Cable 6', 'Cable 9', 'Cable 10', '358288:1.001', '358288:1.002'];
_KM1 = ['-Q1', '358288:10', 'GI L208S', '-KM1', '-Q2', '-S3', 'Cable 13', 'Cable 14', 'Cable 74', 'Cable 7', 'Cable 49', 'Cable 11', 'Cable 12', 'Cable 9', 'Cable 5'];
_Q2 = ['-Q2', 'Cable 18', 'Fuente de Voltaje 24v 5A:1', 'Cable 16', 'Tomacorriente', 'Cable 27', 'Cable 13', '-KM1', 'Cable 14'];
GI_L208S = ['GI L208S', 'Cable 8', '-Q1', 'Cable 6', 'Cable 10', 'Cable 21', '-S3', 'Cable 11', '-KM1', 'Cable 76'];
XD3_24RT_C = ['XD3-24RT-C', 'Cable 44', 'TS3 700-M', 'Cable 17', 'Fuente de Voltaje 24v 5A:1', 'Cable 45', 'Cable 19', 'Cable 60', '-S1', 'Cable 59', '358288:14', 'Cable 61', 'Cable 63', '358288:15', '358288:1.011', 'Cable 64', '358288:17', 'Cable 67', '358288:19', 'Cable 69', '358288:22', 'Cable 72', '-S2', 'Cable 46', 'Cable 36', '-K2', 'Cable 47', 'Cable 48', 'Cable 37', '-K3', 'Cable 57', 'Cable 38', '-K4', 'Cable 39', '-K5', 'Cable 42', '-K6', 'Cable 43', '-K7'];
_K2 = ['-K2', 'Cable 36', 'XD3-24RT-C', 'Cable 32', '-K3', 'Cable 22', 'Cable 15', 'Fuente de Voltaje 24v 5A:1', 'Cable 24', '358288:5'];
_K3 = ['-K3', 'Cable 37', 'XD3-24RT-C', 'Cable 23', '-K4', 'Cable 32', '-K2', 'Cable 25', 'Cable 22', 'Cable 28', '358288:6'];
_K4 = ['-K4', 'Cable 38', 'XD3-24RT-C', 'Cable 29', '-K5', 'Cable 23', '-K3', 'Cable 26', 'Cable 25', 'Cable 31', '358288:7'];
_K5 = ['-K5', 'Cable 39', 'XD3-24RT-C', 'Cable 29', '-K4', 'Cable 35', '-K7', 'Cable 30', '-K6', 'Cable 26', 'Cable 34', '358288:8'];
_K6 = ['-K6', 'Cable 42', 'XD3-24RT-C', 'Cable 52', '-K7', 'Cable 30', '-K5', 'Cable 33', 'Cable 53', '358288:12', 'Cable 54'];
_K7 = ['-K7', 'Cable 43', 'XD3-24RT-C', 'Cable 50', 'Fuente de Voltaje 24v 5A:1', 'Cable 52', '-K6', 'Cable 54', 'Cable 35', '-K5', 'Cable 33', 'Cable 56', '358288:13', 'Cable 55', '358288:11'];
Fuente_de_Voltaje_24v_5A_1 = ['Fuente de Voltaje 24v 5A:1', 'Cable 19', 'XD3-24RT-C', 'Cable 20', '358288:9', 'Cable 17', 'Cable 15', '-K2', 'Cable 58', '358288:21', 'Cable 18', '-Q2', 'Cable 27', 'Cable 50', '-K7'];
_S1 = ['-S1', 'Cable 73', '-S2', 'Cable 60', 'XD3-24RT-C', 'Cable 61'];
_S2 = ['-S2', 'Cable 73', '-S1', 'Cable 72', 'XD3-24RT-C'];
_S3 = ['-S3', 'Cable 21', 'GI L208S', 'Cable 75', 'Cable 74', '-KM1', 'Cable 51', '358288:11', 'Cable 76'];
TS3_700_M = ['TS3 700-M', 'Cable 45', 'XD3-24RT-C', 'Cable 44'];
LP7510 = ['LP7510', 'Señal Pesos', 'Señal a Sumadora', 'PCOM2.1', 'PCOM1.1', 'SP1.1', 'SP2.1', 'RL-Gland PG-9 Iron:5', 'Segmento Comun', 'Señal de Sumadora 2', 'Caja Sumadora', 'PCOM1', 'SP1', 'PCOM2', 'SP2', 'SP1', '358288:16', '358288:17', '358288:18', '358288:19', '358288:1.009', '358288:1.008', '358288:1.004', 'Segmento Señal Peso 2'];

registerOnClick(['ALL_OBJECTS'], false, false, [0,1,2], false, function(event) {

    Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// 1. Configuración de detección' + '\n' +
    'const rect = app.container.getBoundingClientRect();' + '\n' +
    'const mouse = new v3d.Vector2();' + '\n' +
    '' + '\n' +
    'mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;' + '\n' +
    'mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;' + '\n' +
    '' + '\n' +
    '// 2. Raycaster' + '\n' +
    'const raycaster = new v3d.Raycaster();' + '\n' +
    'raycaster.setFromCamera(mouse, app.getCamera());' + '\n' +
    'const intersects = raycaster.intersectObjects(app.scene.children, true);' + '\n' +
    '' + '\n' +
    '// Inicializamos la señal en 0 (No hay coincidencia)' + '\n' +
    'VARS[\'existe_variable\'] = 0;' + '\n' +
    '' + '\n' +
    'if (intersects.length > 0) {' + '\n' +
    '    let obj = intersects[0].object;' + '\n' +
    '    let nombreDetectado = "";' + '\n' +
    '' + '\n' +
    '    // Buscamos el nombre real' + '\n' +
    '    if (obj.parent && (obj.name.includes(\'Mesh\') || obj.name.includes(\'Object\'))) {' + '\n' +
    '        nombreDetectado = obj.parent.name;' + '\n' +
    '    } else {' + '\n' +
    '        nombreDetectado = obj.name;' + '\n' +
    '    }' + '\n' +
    '' + '\n' +
    '    // --- VALIDACIÓN DE SEÑAL ---' + '\n' +
    '    // Si el nombre detectado existe como variable en Puzzles...' + '\n' +
    '    if (VARS[nombreDetectado] !== undefined) {' + '\n' +
    '        ' + '\n' +
    '        VARS[\'objeto_detectado\'] = nombreDetectado; // Pasamos el nombre' + '\n' +
    '        VARS[\'existe_variable\'] = 1;               // ¡Activamos la señal!' + '\n' +
    '        ' + '\n' +
    '        console.log("Señal ACTIVADA para: " + nombreDetectado);' + '\n' +
    '    } else {' + '\n' +
    '        // No hacemos nada con \'objeto_detectado\', la señal se queda en 0' + '\n' +
    '        console.log("Señal RECHAZADA: No hay variable para " + nombreDetectado);' + '\n' +
    '    }' + '\n' +
    '}')))(appInstance, v3d, PL, VARS, PROC);

    console.log(existe_variable);
    if (existe_variable == 1) {
        if (Boton_Activado == 'Ninguno') {
            console.log('Entre a boton activado');

            Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// 1. ASEGURAR POSTPROCESADO Y RENDER PASS' + '\n' +
            'if (!app.postprocessing) {' + '\n' +
            '    app.enablePostprocessing();' + '\n' +
            '}' + '\n' +
            '' + '\n' +
            '// 2. DETECCIÓN (TU LÓGICA)' + '\n' +
            'const raycaster = new v3d.Raycaster();' + '\n' +
            'const mouse = new v3d.Vector2();' + '\n' +
            'const rect = app.container.getBoundingClientRect();' + '\n' +
            '' + '\n' +
            'mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;' + '\n' +
            'mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;' + '\n' +
            '' + '\n' +
            'raycaster.setFromCamera(mouse, app.getCamera());' + '\n' +
            'const intersects = raycaster.intersectObjects(app.scene.children, true);' + '\n' +
            '' + '\n' +
            'if (intersects.length > 0) {' + '\n' +
            '    let obj = intersects[0].object;' + '\n' +
            '    if (obj.parent && (obj.name.includes(\'Mesh\') || obj.name.includes(\'Object\'))) {' + '\n' +
            '        obj = obj.parent;' + '\n' +
            '    }' + '\n' +
            '' + '\n' +
            '    // --- RECONSTRUCCIÓN SEGURA DEL COMPOSER ---' + '\n' +
            '    if (!app.postprocessing.outlinePass) {' + '\n' +
            '        // Bloqueamos el tono para evitar brillos raros' + '\n' +
            '        app.renderer.toneMapping = v3d.NoToneMapping;' + '\n' +
            '' + '\n' +
            '        const composer = app.postprocessing.composer;' + '\n' +
            '        ' + '\n' +
            '        // Buscamos el RenderPass original (la imagen del tablero)' + '\n' +
            '        const renderPass = composer.passes.find(p => p instanceof v3d.RenderPass) ' + '\n' +
            '                           || new v3d.RenderPass(app.scene, app.getCamera());' + '\n' +
            '' + '\n' +
            '        // Creamos el OutlinePass' + '\n' +
            '        const oPass = new v3d.OutlinePass(' + '\n' +
            '            new v3d.Vector2(window.innerWidth, window.innerHeight), ' + '\n' +
            '            app.scene, ' + '\n' +
            '            app.getCamera()' + '\n' +
            '        );' + '\n' +
            '        ' + '\n' +
            '        oPass.edgeStrength = 5;' + '\n' +
            '        oPass.edgeThickness = 1.5;' + '\n' +
            '        oPass.visibleEdgeColor.set(0x00ff00); // Verde' + '\n' +
            '        oPass.hiddenEdgeColor.set(0x003300);  // Verde oscuro para lo tapado' + '\n' +
            '        oPass.renderToScreen = true; // <--- ESTO EVITA QUE SE PONGA NEGRO' + '\n' +
            '' + '\n' +
            '        // Reensamblamos: primero la realidad, luego la silueta' + '\n' +
            '        composer.passes = [renderPass, oPass];' + '\n' +
            '        app.postprocessing.outlinePass = oPass;' + '\n' +
            '' + '\n' +
            '        // Sincronización de cámara en tiempo real' + '\n' +
            '        if (!app.renderCallbacks.includes(updateOutlineCamera)) {' + '\n' +
            '            app.renderCallbacks.push(updateOutlineCamera);' + '\n' +
            '        }' + '\n' +
            '    }' + '\n' +
            '' + '\n' +
            '    app.postprocessing.outlinePass.selectedObjects = [obj];' + '\n' +
            '' + '\n' +
            '    // Variables de Puzzles' + '\n' +
            '    VARS[\'objeto_detectado\'] = obj.name;' + '\n' +
            '    VARS[\'existe_variable\'] = (VARS[obj.name] !== undefined) ? 1 : 0;' + '\n' +
            '' + '\n' +
            '} else {' + '\n' +
            '    if (app.postprocessing?.outlinePass) {' + '\n' +
            '        app.postprocessing.outlinePass.selectedObjects = [];' + '\n' +
            '    }' + '\n' +
            '}' + '\n' +
            '' + '\n' +
            '// Función de soporte (definirla una sola vez o dejarla fuera)' + '\n' +
            'function updateOutlineCamera() {' + '\n' +
            '    if (app.postprocessing?.outlinePass) {' + '\n' +
            '        app.postprocessing.outlinePass.renderCamera = app.getCamera();' + '\n' +
            '    }' + '\n' +
            '}')))(appInstance, v3d, PL, VARS, PROC);


            Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('const nombreABuscar = VARS[\'objeto_detectado\'];' + '\n' +
            '' + '\n' +
            '// CORRECCIÓN: Si VARS[nombreABuscar] no existe, usamos una lista vacía []' + '\n' +
            'const objetosAEstudiar = VARS[nombreABuscar] || []; ' + '\n' +
            '' + '\n' +
            'const materialesExcepcion = [\'-K2_Mat.318\', \'-K3_Mat.318\', \'-K4_Mat.318\',\'-K5_Mat.318\', \'-K6_Mat.318\', \'-K7_Mat.318\'];' + '\n' +
            'const opacidadFondo = 0.04; ' + '\n' +
            '' + '\n' +
            '' + '\n' +
            'app.scene.traverse(obj => {' + '\n' +
            '    if (obj.isMesh && obj.material) {' + '\n' +
            '        ' + '\n' +
            '        // Ahora .includes() no fallará porque objetosAEstudiar siempre será al menos []' + '\n' +
            '        const esProtegido = objetosAEstudiar.includes(obj.name) || ' + '\n' +
            '                            (obj.parent && objetosAEstudiar.includes(obj.parent.name));' + '\n' +
            '' + '\n' +
            '        const mats = Array.isArray(obj.material) ? obj.material : [obj.material];' + '\n' +
            '' + '\n' +
            '        mats.forEach(mat => {' + '\n' +
            '            mat.transparent = true;' + '\n' +
            '            ' + '\n' +
            '            if (materialesExcepcion.includes(mat.name)) {' + '\n' +
            '                mat.opacity = 0.2;' + '\n' +
            '                if (mat.nodeValue) mat.nodeValue.fill(0.2);' + '\n' +
            '            } ' + '\n' +
            '            else if (esProtegido) {' + '\n' +
            '                mat.opacity = 1;' + '\n' +
            '                if (mat.nodeValue) mat.nodeValue.fill(1.0);' + '\n' +
            '            } else {' + '\n' +
            '                mat.opacity = opacidadFondo;' + '\n' +
            '                if (mat.nodeValue) mat.nodeValue.fill(opacidadFondo);' + '\n' +
            '            }' + '\n' +
            '            ' + '\n' +
            '            mat.needsUpdate = true;' + '\n' +
            '        });' + '\n' +
            '    }' + '\n' +
            '});')))(appInstance, v3d, PL, VARS, PROC);

            Boton_Activado = objeto_detectado;
            objeto_detectado = 'Ocupado';
            console.log(Boton_Activado);
            console.log(objeto_detectado);
        } else {
            console.log('Llegue aqui');

            Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// 1. Configuración de detección (Corrección de clic)' + '\n' +
            'const rect = app.container.getBoundingClientRect();' + '\n' +
            'const mouse = new v3d.Vector2();' + '\n' +
            '' + '\n' +
            'mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;' + '\n' +
            'mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;' + '\n' +
            '' + '\n' +
            '// 2. Raycaster' + '\n' +
            'const raycaster = new v3d.Raycaster();' + '\n' +
            'raycaster.setFromCamera(mouse, app.getCamera());' + '\n' +
            'const intersects = raycaster.intersectObjects(app.scene.children, true);' + '\n' +
            '' + '\n' +
            'let nombreParaPuzzle = "ninguno";' + '\n' +
            '' + '\n' +
            'if (intersects.length > 0) {' + '\n' +
            '    let obj = intersects[0].object;' + '\n' +
            '    ' + '\n' +
            '    // Si el nombre es genérico, buscamos al padre' + '\n' +
            '    if (obj.parent && (obj.name.includes(\'Mesh\') || obj.name.includes(\'Object\'))) {' + '\n' +
            '        nombreParaPuzzle = obj.parent.name;' + '\n' +
            '    } else {' + '\n' +
            '        nombreParaPuzzle = obj.name;' + '\n' +
            '    }' + '\n' +
            '}' + '\n' +
            '' + '\n' +
            '// 3. VINCULACIÓN CORRECTA (Para v4.12.0)' + '\n' +
            '// En lugar de v3d.puzzles.vars, usamos el objeto VARS directamente' + '\n' +
            'VARS[\'objeto_detectado\'] = nombreParaPuzzle;' + '\n' +
            '' + '\n' +
            'console.log("Variable \'objeto_detectado\' enviada a Puzzles: " + nombreParaPuzzle);')))(appInstance, v3d, PL, VARS, PROC);

            if (Boton_Activado == objeto_detectado) {
                objeto_detectado = 'Ocupado';

                Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('// 1. COMPROBACIÓN DE SEGURIDAD (Por si no se ha inicializado el post-processing)' + '\n' +
                'if (!app.postprocessing) {' + '\n' +
                '    app.enablePostprocessing();' + '\n' +
                '}' + '\n' +
                '' + '\n' +
                '// 2. CONFIGURACIÓN DEL RAYCASTER (EL "PUNTERO" INVISIBLE)' + '\n' +
                'const raycaster = new v3d.Raycaster();' + '\n' +
                'const mouse = new v3d.Vector2();' + '\n' +
                'const rect = app.container.getBoundingClientRect();' + '\n' +
                '' + '\n' +
                '// Convertimos la posición del mouse al espacio 3D de la cámara' + '\n' +
                'mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;' + '\n' +
                'mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;' + '\n' +
                '' + '\n' +
                'raycaster.setFromCamera(mouse, app.getCamera());' + '\n' +
                '' + '\n' +
                '// Buscamos qué objetos atravesó el "rayo" del clic' + '\n' +
                'const intersects = raycaster.intersectObjects(app.scene.children, true);' + '\n' +
                '' + '\n' +
                '// 3. LÓGICA DE DETECCIÓN Y RESALTADO' + '\n' +
                'if (intersects.length > 0) {' + '\n' +
                '    let obj = intersects[0].object;' + '\n' +
                '' + '\n' +
                '    // Subir al padre si el objeto es parte de un grupo (común en modelos CAD/Inventor)' + '\n' +
                '    if (obj.parent && (obj.name.includes(\'Mesh\') || obj.name.includes(\'Object\'))) {' + '\n' +
                '        obj = obj.parent;' + '\n' +
                '    }' + '\n' +
                '' + '\n' +
                '    // Accedemos al OutlinePass (la silueta)' + '\n' +
                '    const outline = app.postprocessing.outlinePass;' + '\n' +
                '' + '\n' +
                '    if (outline) {' + '\n' +
                '        // --- AQUÍ ESTÁ EL TRUCO DEL TOGGLE ---' + '\n' +
                '        ' + '\n' +
                '        // ¿El objeto que tocamos ya está en la lista de resaltados?' + '\n' +
                '        const estaSeleccionado = outline.selectedObjects.includes(obj);' + '\n' +
                '' + '\n' +
                '        if (estaSeleccionado) {' + '\n' +
                '            // SI YA ESTABA: Lo quitamos (Limpiamos la selección)' + '\n' +
                '            outline.selectedObjects = [];' + '\n' +
                '            VARS[\'objeto_detectado\'] = ""; // Limpiamos variable de Puzzle' + '\n' +
                '            console.log("Desmarcado:", obj.name);' + '\n' +
                '        } else {' + '\n' +
                '            // SI NO ESTABA: Lo marcamos (Ponemos la silueta)' + '\n' +
                '            outline.selectedObjects = [obj];' + '\n' +
                '            VARS[\'objeto_detectado\'] = obj.name; // Guardamos para Puzzles' + '\n' +
                '            console.log("Marcado:", obj.name);' + '\n' +
                '        }' + '\n' +
                '    }' + '\n' +
                '' + '\n' +
                '    // Actualizamos si existe lógica personalizada para este componente' + '\n' +
                '    VARS[\'existe_variable\'] = (VARS[obj.name] !== undefined) ? 1 : 0;' + '\n' +
                '' + '\n' +
                '} else {' + '\n' +
                '    // OPCIONAL: Si haces clic al fondo (al aire), quitar el resaltado actual' + '\n' +
                '    if (app.postprocessing?.outlinePass) {' + '\n' +
                '        app.postprocessing.outlinePass.selectedObjects = [];' + '\n' +
                '        VARS[\'objeto_detectado\'] = "";' + '\n' +
                '    }' + '\n' +
                '}' + '\n' +
                '' + '\n' +
                '// --- FUNCIÓN DE SOPORTE PARA LA CÁMARA ---' + '\n' +
                '// (Verge3D necesita saber si moviste la cámara para que la silueta no se desfase)' + '\n' +
                'if (!app.renderCallbacks.includes(actualizarCamaraOutline)) {' + '\n' +
                '    app.renderCallbacks.push(actualizarCamaraOutline);' + '\n' +
                '}' + '\n' +
                '' + '\n' +
                'function actualizarCamaraOutline() {' + '\n' +
                '    if (app.postprocessing?.outlinePass) {' + '\n' +
                '        app.postprocessing.outlinePass.renderCamera = app.getCamera();' + '\n' +
                '    }' + '\n' +
                '}')))(appInstance, v3d, PL, VARS, PROC);


                Function('app', 'v3d', 'puzzles', 'VARS', 'PROC', (('const nombreABuscar = VARS[\'objeto_detectado\'];' + '\n' +
                '' + '\n' +
                '// CORRECCIÓN: Si VARS[nombreABuscar] no existe, usamos una lista vacía []' + '\n' +
                'const objetosAEstudiar = VARS[nombreABuscar] || []; ' + '\n' +
                '' + '\n' +
                'const materialesExcepcion = [\'-K2_Mat.318\', \'-K3_Mat.318\', \'-K4_Mat.318\',\'-K5_Mat.318\', \'-K6_Mat.318\', \'-K7_Mat.318\'];' + '\n' +
                'const opacidadFondo = 1; ' + '\n' +
                '' + '\n' +
                'app.scene.traverse(obj => {' + '\n' +
                '    if (obj.isMesh && obj.material) {' + '\n' +
                '        ' + '\n' +
                '        // Ahora .includes() no fallará porque objetosAEstudiar siempre será al menos []' + '\n' +
                '        const esProtegido = objetosAEstudiar.includes(obj.name) || ' + '\n' +
                '                            (obj.parent && objetosAEstudiar.includes(obj.parent.name));' + '\n' +
                '' + '\n' +
                '        const mats = Array.isArray(obj.material) ? obj.material : [obj.material];' + '\n' +
                '' + '\n' +
                '        mats.forEach(mat => {' + '\n' +
                '            mat.transparent = true;' + '\n' +
                '            ' + '\n' +
                '            if (materialesExcepcion.includes(mat.name)) {' + '\n' +
                '                mat.opacity = 0.2;' + '\n' +
                '                if (mat.nodeValue) mat.nodeValue.fill(0.2);' + '\n' +
                '            } ' + '\n' +
                '            else if (esProtegido) {' + '\n' +
                '                mat.opacity = 1;' + '\n' +
                '                if (mat.nodeValue) mat.nodeValue.fill(1.0);' + '\n' +
                '            } else {' + '\n' +
                '                mat.opacity = opacidadFondo;' + '\n' +
                '                if (mat.nodeValue) mat.nodeValue.fill(opacidadFondo);' + '\n' +
                '            }' + '\n' +
                '            ' + '\n' +
                '            mat.needsUpdate = true;' + '\n' +
                '        });' + '\n' +
                '    }' + '\n' +
                '});')))(appInstance, v3d, PL, VARS, PROC);

                Boton_Activado = 'Ninguno';
                console.log(Boton_Activado);
                console.log(objeto_detectado);
            }
        }
    } else {
    }
}, function(event) {});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
